defaults:
  - _self_
  - task: pusht_lowdim

name: train_diffusion_unet_lowdim
_target_: diffusion_policy.workspace.train_diffusion_unet_lowdim_workspace.TrainDiffusionUnetLowdimWorkspace

obs_dim: ${task.obs_dim}
action_dim: ${task.action_dim}
keypoint_dim: ${task.keypoint_dim}
task_name: ${task.name}
exp_name: "default"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_local_cond: False
obs_as_global_cond: True
pred_action_steps_only: False

policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy.DiffusionUnetLowdimPolicy

  model:
    _target_: diffusion_policy.model.diffusion.conditional_unet1d.ConditionalUnet1D
    input_dim: "${eval: ${task.action_dim} if ${obs_as_local_cond} or ${obs_as_global_cond} else ${task.obs_dim} + ${task.action_dim}}"
    local_cond_dim: "${eval: ${task.obs_dim} if ${obs_as_local_cond} else None}"
    global_cond_dim: "${eval: ${task.obs_dim}*${n_obs_steps} if ${obs_as_global_cond} else None}"
    diffusion_step_embed_dim: 256
    down_dims: [256, 512, 1024]
    kernel_size: 5
    n_groups: 8
    cond_predict_scale: True
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    # beta_schedule is important
    # this is the best we found
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: epsilon # or sample

  horizon: ${horizon}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 8
  obs_as_local_cond: ${obs_as_local_cond}
  obs_as_global_cond: ${obs_as_global_cond}
  pred_action_steps_only: ${pred_action_steps_only}
  oa_step_convention: True

  # scheduler.step params
  # predict_epsilon: True
  use_clipped_model_output: True

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 256
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: False

pac_dataloader:
  batch_size: 256
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: False
  
val_dataloader:
  batch_size: 256
  num_workers: 1
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:1"
  seed: 42
  debug: False
  resume: False
  retrain: False
  desired_ckpt_path: "data/outputs/2025.10.12/11.33.45_train_diffusion_unet_lowdim_pusht_lowdim/checkpoints/epoch=0400-test_mean_score=0.780.ckpt"
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 500
  gradient_accumulate_every: 1
  use_ema: True
  # training loop control
  # in epochs
  rollout_every: 50
  checkpoint_every: 50
  val_every: 1
  sample_every: 50
  reconstraction_every: 50
  nll_every: 50
  memorization_every: 50
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  PAC_loss_type: "Norm"
  random_timestep: False
  # PAC-Bayes Bounds 
  num_expect: 10
  diam: 2
  delta: 0.05

logging:
  project: diffusion_policy_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

checkpoint_every:
  topk:
    monitor_key: epoch
    format_str: 'epoch={epoch:04d}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

checkpoint_nll:
  topk:
    monitor_key: test_nll_bpd
    mode: min
    k: 1
    format_str: 'epoch={epoch:04d}-nll_bpd={test_nll_bpd:.3f}.ckpt'
  save_last_ckpt: False
  save_last_snapshot: False

checkpoint_val:
  topk:
    monitor_key: test_noise_pred_loss
    mode: min
    k: 1
    format_str: 'epoch={epoch:04d}-test_noise_pred_loss={test_noise_pred_loss:.3f}.ckpt'
  save_last_ckpt: False
  save_last_snapshot: False
  
multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
